import React from "react";

import "./BashPortrait.scss";

const BashPortrait = () => {
   return(
   <div className="bash-portrait">
      
      <span className="bash-portrait__ln ln-pic1"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*****////(##(//@@@****@@@@@@@@@@@*/***@@@@@@@@*/@@*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic1"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"***@@@**@@/(###(((//**/(#/@@@@@@*/(((//**/*//(/**/#%(*@@@@@@@@@@@@@@@###@%"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic1"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"&&*******@@@&**/(##%#####(((######/*//##%%#(/****/(%%%%#(((****/***&@@@@@/*//(/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic1"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/((*@#*/////(((((//#((#%%%%####%%###%%%%%%%%%######%%%%%%%%%#(((//**(((#######(#####((//*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic2"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"((/(##%(*&*//(((#%%#(##%####%%%%%%%%%%%%%%%%%%%%%%%###%%%%%%%%%%%%%#(#####(######%%###%#/**(@@@&/((#***"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic2"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/##%##(/////#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%&%&%%%%%%%%%%%%%%%%###%%#####(//*&@@@@@@@@//**"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic2"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"**////(%%#(((/(#%##%%%%%%%%%%%%%%%%%%&&&&&&&%%%%&&&&&%%%%%%%%%&&&&&&%%%&&&&&%%%%%%%%%%%%%%#(//*%*/***&&@@***/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic2"><span className="bash-portrait__bg">{"@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"#//&@@@@/(###%%%%###%##((%%%%%%%%%%%%%%%%%%&%%&&&&&&&&&&&&&&&&%%#%%&&&&&&&&&&&&&&&&&&&&&&&%%%%%%%%#(((//**&***@@@*****"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic2"><span className="bash-portrait__bg">{"@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*/*@#*@@@@##*/(%%##(((#%%%%&%%%%%%%%%&%%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%%%#(#(######%#/**/////*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic2"><span className="bash-portrait__bg">{"@@@@@@@@@@"}</span><span className="bash-portrait__content">{"((@@@&@@@@(/(##%##%##%%%%%%%%%&%%%&&%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%%##%%%%%%((/(((###(/(**"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic3"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*/#%&&&&&&%%%%%%%%%&%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%%%%%%%%%###(((//*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic3"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*/((((##(##%%%%%%%%%%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@&&&&&&&&&&&&&&&&&&&&&&&&&&%%%%%%###(((/***%&"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic3"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"%(%%%%%%%%%&&##%%%%%%%%&&&%&&&&&&&&&&&&&&&&&&&&&&&&&&&@&&&&&&&&&&&@@@&&&&@&&@@&&&&&&&&&&&&&&&&&&&&&%&&&&&&&%%&%%#(#%###*@@///@@@@*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic3"><span className="bash-portrait__bg">{"@@@@@@@"}</span><span className="bash-portrait__content">{"/(/((#%#((((((/(#%&&&&&&&&&&&&&&&&&&&&&&@@&&&&&&&&&&&@@&&@&&@&&&@&&&&@@@@@@@@@@&&@@&&@@@@&&&&&&&&&&&&&&%&&&&%%%%%%%%%#####(((****@**//%"}</span><span className="bash-portrait__bg">{"@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic3"><span className="bash-portrait__bg">{"@@@@@@@@"}</span><span className="bash-portrait__content">{"*(%%#((//(((####(#%&&&%%%&&&&&&&&&&@@@@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@&&&&&&&&&&&&&&&&&&&&&&&&%%&&&&%&%%%%%%%###%##%#(*&@*//(///"}</span><span className="bash-portrait__bg">{"@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic3"><span className="bash-portrait__bg">{"@@@@@@@"}</span><span className="bash-portrait__content">{"*(#%###%%#((#%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&@@@&&&&&&&%%&%%%&&&&&&%%&&&&%%%%%%%%%%%%%%###(/*//(//"}</span><span className="bash-portrait__bg">{"@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic4"><span className="bash-portrait__bg">{"@@@@@@@"}</span><span className="bash-portrait__content">{"/(#%%%&%%#%%%%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%%%%%%%%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%&&&&&&&%%%%%%%%%%%##%%##(**((((/"}</span><span className="bash-portrait__bg">{"@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic4"><span className="bash-portrait__bg">{"@@@@@@"}</span><span className="bash-portrait__content">{"*(#%%&&%%%#%%%&&&&&&&&&&%&&&&&&&&@@@@@&&&&&&&&&&&&&&&&&&%%&&%%%%%%%%%###%%%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%&%%&%%%%%%%%%%&%#%#(/&**(#/"}</span><span className="bash-portrait__bg">{"@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic4"><span className="bash-portrait__bg">{"@@@@@@"}</span><span className="bash-portrait__content">{"*(#%%%%%##%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%%%%%%%%%%%%%#((##########%%%%%%%&&&%%&&&&%&&&&&&&&&&&&&&&&&&&&&&&%%&&&&&&&&&%%%%%#//@#(#&"}</span><span className="bash-portrait__bg">{"@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic4"><span className="bash-portrait__bg">{"@@@@@@@"}</span><span className="bash-portrait__content">{"*#%%%%%%%%%%%&&&&&&&&&&&&&&&&&&&&&&&&&&&%%###(((####%#%##((((((((##((######%%%%%%%%%&%%%&%%%%&%%%&&%&&&&&&&&&&&&&&%%%&&&&&&&&%%%%##//(#/"}</span><span className="bash-portrait__bg">{"@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic4"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"(####%%%%%%&&&&&&&&&&&&&&&&&&&&&&&&%#((((////((((((((////////////(((((((((((#%%#########%%%%%%%%%%%&&&&&&&&&&&&&&&%&&&&&&&%%%%%%#%#(#"}</span><span className="bash-portrait__bg">{"@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic4"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"/(##%%%%%%%&&&&&&&&&&%&&&&&&&&&&&%#((//////////////*********///////**//////////(######(((((##%%%%%%%%%%&&&&&&&&&&&&&%&&&&&%%%%%%%%##/"}</span><span className="bash-portrait__bg">{"@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic5"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"//(#%%%%%%%%%&&&&%%%%&&&&&&&&&&%#(///////////******************///*/****//////////((((((((((/((((((((###%%&&&&&&&&&&&&&&&&&%%%%%%#####(/"}</span><span className="bash-portrait__bg">{"@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic5"><span className="bash-portrait__bg">{"@@@@@@@@"}</span><span className="bash-portrait__content">{"&/#%%%%%%%%&&&&&&&&&&&&&&&&&&%#((/////////////////*****/*//**********************//*/*//((/////////////(###%%%&&&&&&&%%%&&&&&%%%%%%%%%%#(*/"}</span><span className="bash-portrait__bg">{"@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic5"><span className="bash-portrait__bg">{"@@@@@@@@"}</span><span className="bash-portrait__content">{"*/##%%%%%%%%&&&&&%%&&&&&&&&%#((////////////**********/*****///***************************************////((##%%&&&&&&&&&&&&&%%%%%%%%###(//*"}</span><span className="bash-portrait__bg">{"@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic5"><span className="bash-portrait__bg">{"@@@@@@@"}</span><span className="bash-portrait__content">{"**/(###%%%%%&&&&&&%&&&&&&&%%((//////////////////////////////*********************************************//((##%%%&&&&&&&&&&&%%%%%%%%##(#(*"}</span><span className="bash-portrait__bg">{"@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic5"><span className="bash-portrait__bg">{"@@@@@@"}</span><span className="bash-portrait__content">{"*((/*(%%%%%%%%%%&%&&&&&&&%%#((///////////////////////////***************************************************//((##%%&&&&&&&&&&%%%%%%######/"}</span><span className="bash-portrait__bg">{"@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic5"><span className="bash-portrait__bg">{"@@@@@@"}</span><span className="bash-portrait__content">{"/(###%%%%%%%%&&&&&&&&&&&%%#((/////////////////////////////*/*******************/////*************************//((##%%&&&&&&&&&&%%%%%%%#((//*"}</span><span className="bash-portrait__bg">{"@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic6"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"/#%%%%%&&&&&&&&&&&&%%%#(/////////////((((/(((((((##(((/////*****************///((///((((((//////***********///((#%%&&&&&&%%&%%%%%%%%#(//****"}</span><span className="bash-portrait__bg">{"@"}</span></span>
      <span className="bash-portrait__ln ln-pic6"><span className="bash-portrait__bg">{"@@@@@@@@"}</span><span className="bash-portrait__content">{"*/(%%%%%&&&&&&&&&&&&&%#((///////(((((#((######%%%######((///***************////((#(((#####((#####((//////****///((#%%%&&&&&&%%%%%%#######((/*/"}</span></span>
      <span className="bash-portrait__ln ln-pic6"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"/#%%%%%%&&&&&&&&&&&%#(//////(########%%%%%%%%%#######((((/******************//((((((##################(((/**////((#%%%&&&&&&%%%%%#%%#####((//"}</span></span>
      <span className="bash-portrait__ln ln-pic6"><span className="bash-portrait__bg">{"@@@@@@@@"}</span><span className="bash-portrait__content">{"*/##((///(%%%%&&&&&&%((////(#########(((((((((((((((////////*****************//////(/((((/((((((((((((####(/***////(#%%%%&%&%%%%%%%%%%%##((*"}</span><span className="bash-portrait__bg">{"@@"}</span></span>
      <span className="bash-portrait__ln ln-pic6"><span className="bash-portrait__bg">{"@@@@@@@@@@"}</span><span className="bash-portrait__content">{"%*/(##((%%%&&&&&&%#(///(###(//*//*******************************************************************////((((/////(#%%&%%%%%&&%%%%%%####(/*"}</span><span className="bash-portrait__bg">{"@@"}</span></span>
      <span className="bash-portrait__ln ln-pic6"><span className="bash-portrait__bg">{"@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*(%%%%%%%%%%%&&&&%#(//###/***********//******************************************************************/((((//((#%%%%%%%%%%%%%#####/*"}</span><span className="bash-portrait__bg">{"@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic7"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"/#####%%%%%%%&&&&&%#/((#(//***********//********/**********************************************************///(//(###%%%%%%%%%%%%%##(/**@*"}</span><span className="bash-portrait__bg">{"@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic7"><span className="bash-portrait__bg">{"@@@@@@@@@@"}</span><span className="bash-portrait__content">{"&////(##%%#%%&%%%%((((//*****************************************************/////***************************/(/(###%%%%%%%%%%%%%##//"}</span><span className="bash-portrait__bg">{"@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic7"><span className="bash-portrait__bg">{"@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"%*/////(%%%%%%%%(///******/**/////***///////////******//////******************/******************,**********///(##%%%%%%%%%%%%##(****"}</span></span>
      <span className="bash-portrait__ln ln-pic7"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"***(%%%%%%%%%%(///*****///////////((####(/////******///////////************///////////*********************///(#%%%%%%%%%%%%%#((###(/"}</span><span className="bash-portrait__bg">{"@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic7"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/#%%%%%%%%%#//*****////////#%%&&&%(#&%%#///((/**////////////************//////((%%%&&%%#(/****************///(#%%%%%%%%%%%%%(((((/"}</span><span className="bash-portrait__bg">{"@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic7"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/%%%%%%&&%(/***/**////(#%%#(/(%%%%&%%#/*///((/////////////*******/*****/(#(//*/#%%%&&%%%%#%#(/*************/(#%%%%%%%%%%%#((///*"}</span><span className="bash-portrait__bg">{"@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic8"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*(%%%%%%%(/*****////((((((((((((((/////////////////////**********/***////////((#%%%%%#(///(###(//**********/(%%%%%%%%%%##//*"}</span><span className="bash-portrait__bg">{"@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic8"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/(##%%%%%(/****////////////////((////////(///////////******************/////////////((((///*///************/(#%%%%%%%%####/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic8"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*#%%%%%%#(/*****/////////////////////////////////////*********************//////////////*************,,,****/#%%%%%%#####/*#"}</span><span className="bash-portrait__bg">{"@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic8"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/(#%%%%#/*******//////////*//*//////////**/////////*****************************/*******************,,*****/#%%%%%%%###(//"}</span><span className="bash-portrait__bg">{"@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic8"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*/#%%#/*********************///**//****/////////*******************************************,****,,,,*,***/#%%%####%#(/"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic8"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*/(#(/*******************************/**////*******************************************,,,,,,,,,,,,,*****(#%#%##(/"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic9"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/#(/*********************************///***************,,,******************************,,,,,,,,,,****/(####(//"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic9"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*((/*********************************//**********,**************************************,,,,,,,,,,,,,*/(((/@/"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic9"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*(#/********************************//**//////****************************,***************,,,,,,,,,,**/(((*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic9"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/#(********************************////(##%#(*/**////(%%%%(/***************,*,,,*,,,,,****,,,,,,,,***/((/"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic9"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"((/*******************************///////(((/////////((#(//////**************,,,,,,**,,,,,,,,,,,,***(#(/"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-pic9"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*((******************************/////((/////////////////////******************,,,*******,,,,,,,,**/((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picA"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"((/***************************///////((((////////*/////////******************,*,**********,,,,*,**(((*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picA"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*(//*************************///////(((((((((/////(((/((///********************************,,,***//**"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picA"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*//***********************//////(((#########((((##(((((((////***********************************//"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picA"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"///********************/////(((((###########((((###(#(((((/////*******************************//"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picA"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/////*////***********////(((((((((((////////(((////*////((/////////**************************/(("}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picA"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"(///////////*******//(((((((////*/**///////***//////////**//////////***************//////*////"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picB"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*((/((/((///*/**////(////////////////////(((((///////////////*///////*/**********/*//////////%"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picB"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"(((((((((////***////////////////(((((((((((((((((((((((/////////**************///////(///((*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picB"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/(((((((((((/////*/////(#######(####((##########(((((((#######(/////*********//((((////(((/"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picB"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"(((((((##(((/////**//////(((((((((((((((((((/((/(///////////////////*/****///(((((((((((*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picB"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/(((#(###(((//////////////////////(//////////////////*****************/*/////((((((////"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picB"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/((######((////////////////////////////((//////////***************///////((((((((((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picC"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/######(((////////////////////////(((((((((((////////////**//*/*/*/////((/(((((((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picC"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"//#####(((////////////////////((((((((#((##((((((//////////////////////((((((((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picC"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*(####((//////////////////////////((((((((((/////////////////////////(((((((((/"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picC"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/####((((/((///////////////////(////////(/////////////////////////(((((((**"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picC"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"/####((((////////////////////////////////////////////////////((((((((*****"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picC"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*/#%%###((/////////////////////////////////////////////////(((((/*************"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picD"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*********//((######((/////(((///////////////////////////////////(((##(/******/#####(((///("}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picD"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*********/*/**////////////(####(((((#((((/(///((((((((((////////((////(((####(//*******/#%%%####((//(((*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picD"><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@"}</span><span className="bash-portrait__content">{"*/(##(#########(##########///////////(########(((((((((((((((((((((((((((((((((###((/**//*****/(####%%###(((//(((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picD"><span className="bash-portrait__bg">{"@@@@@@@@@"}</span><span className="bash-portrait__content">{"((((######%%%%#%########%#%#####/////////////###%#########((####(((((#(#(((##########((/////********/######%%##(((//(((((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picD"><span className="bash-portrait__bg">{"@@@@@@"}</span><span className="bash-portrait__content">{"/((#####%%%%%%%%#########%%%%%%%%%%///////////////(##%%%%%%####################%######(////(//*********/#%####%%##((((//(((((/#"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picD"><span className="bash-portrait__bg">{"@@@"}</span><span className="bash-portrait__content">{"*(((#####%%%&&&&%########%%%%&&&&&&&&#///////*/////////((###%%%#%#%#%%%%#####%%###(###((///////*********///#%####%%###((((/(((((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picE"><span className="bash-portrait__content">{"/((#####%&%######%%%%%%%&&&&&&&&&%(((//////////////////////////////(/////////////////////////////*******//////#####%%###((((//(((((/*%"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picE"><span className="bash-portrait__content">{"//((#####%%%%###%&%%###%%%%%%&&&&&&&#((//////////////////////(#(######((//(///((((###((/////////*********/////#%####%###(((((/(((((/*"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picE"><span className="bash-portrait__content">{"((#####&&%%#######%&&&@@@&&&&&&&&((////((///////////////////////////////////////////////////////*//*****/////(%####%##(((((((#(((((/(/**&"}</span><span className="bash-portrait__bg">{"@@@@@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picE"><span className="bash-portrait__content">{"(#####%&%%#########&@@@@@&@&&&&&%(////((////////////////////////////////////////*///////////////////**//////(%####%###((((((((((((/((((((//*%"}</span><span className="bash-portrait__bg">{"@@@@@@@@@"}</span></span>
      <span className="bash-portrait__ln ln-picE"><span className="bash-portrait__content">{"(#####%&%%########%%&@@@@@&&&&&&%(////((////////////////////////////////////////////////////////*///*/////((#####%%##(((((((#(((((/((((((((//***@**/**"}</span></span>
      <span className="bash-portrait__ln ln-picE"><span className="bash-portrait__content">{"((####%&&%#########%%@@@@@@@@&&&&(/(/(((//////////////////////////////////**/////////////////////*///////(######%%##(((((((((((((((((((((((///********"}</span></span>
      <span className="bash-portrait__ln ln-picF"><span className="bash-portrait__content">{"((#####&&%%#########%%@@@@@@@@&&&%/(((((////////////////////////////////////////////////////*///(//////((######%####(((((((#(((((((((((((((((#(((/**//"}</span></span>
      <span className="bash-portrait__ln ln-picF"><span className="bash-portrait__content">{"(((####%%&%%%######%%%%&@@@@@@@&&&#(((//////////////////////////////////////////////////////*////////((######%%%###(((((((#((((((((((((((((###((#####("}</span></span>
      <span className="bash-portrait__ln ln-picF"><span className="bash-portrait__content">{"((((#####%&%%#########%%&@@@@@@&&&%(((/////////////////////////////////////////////////////////////(((######%%%###(((((((#((((((((((((((((%##(((((####"}</span></span>
      <span className="bash-portrait__ln ln-picF"><span className="bash-portrait__content">{"(((((######&&%%%#######%%&@@@@@@&&&%((//////////////////////////////////(((///////////////////////((######%%%####(((((((#(((((((/(((((((#######(((####"}</span></span>
      <span className="bash-portrait__ln ln-picF"><span className="bash-portrait__content">{"(((((########%%%%%#####%%%%@@@@&&&&&%(//////////////////////////////////////////////////////////(((%####%%%%####(#(((((#(((((((((((((((#######((((####"}</span></span>
      <span className="bash-portrait__ln ln-picF"><span className="bash-portrait__content">{"##((((((######%&&%%%####%%%%&@@&&&&&&%#(//////////////////////////////////////////////////////(((%######%%%#####(((((#(###(((((((((((##########((((###"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"###%%(((((((#####%&&%%#####%%&@@@@&&&&&#((//////////////////////////////////////////////////(((%####%%%%%##(###(((((#(((((((((((((#%###((#####((((####"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"####%%%#((((#######%&&%%####%%%@@@&@&&&&%##(//////////////////////////////////////////////((#######%%%%######(((((##((((((((##(#%%#####((#####(######%"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"####%%%%%#(((((#######&&%%%##%%%&@@@@@@&&&%%#((((((//////////////////////////////////////((%%#####%%%%#######((((###(##((((##%%%%%#######(((##(#######"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"######%%%%#%#((((######%%&&%%%%%%%@@@@@@&&&%%%##(((((/////////////////////////////////((#%%#####%%%%#####(##((((##########%%%%%%%#####################"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"########%%%#%%%(((########%&%%%%%%%&@@@@@&&&&%%%###((((////////////////////////////(((#&&#####%%%%######((((####((####%%%%%%%%#########(#(#(((##(#####"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"#########%%%%%%%%(##(#(######%&%%%%%&@@@@&@&&&&%%%%%###((////////////////(//////((#%&&%#####%%%%########((((######%%%%%%%%%%%################(########"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"#########%%%&%%%%%#(((##(##(###%&%%%%%&@@@@@&&&&&%%%%%%####(((((((((////(/((((###&@&&%###%%%%%################%%%%%%%%%%%%%%####(########(###(########"}</span></span>
      <span className="bash-portrait__ln ln-picG"><span className="bash-portrait__content">{"%########%%%%%&#%%%%#(/((((((#####%%%%&&@@@@@@&&@&&%%%%%%%##########(#########&@&&&%#%%%%%&###########(###%%#%%#%%%%%%%%%%####################(#######"}</span></span>
   </div>
)
}

export default BashPortrait;

